// <auto-generated />
using System;
using Coworking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coworking.Migrations
{
    [DbContext(typeof(TrenirovkaContext))]
    [Migration("20260503104558_AddedRoomEquipmentRelation")]
    partial class AddedRoomEquipmentRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coworking.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("BookingStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_status_id");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("booking_pkey");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.BookingStatus", b =>
                {
                    b.Property<int>("BookingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingStatusId"));

                    b.Property<string>("BookingStatusName")
                        .HasColumnType("character varying")
                        .HasColumnName("booking_status_name");

                    b.HasKey("BookingStatusId")
                        .HasName("booking_status_pkey");

                    b.ToTable("booking_status", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("EquipmentName")
                        .HasColumnType("character varying")
                        .HasColumnName("equipment_name");

                    b.HasKey("EquipmentId")
                        .HasName("equipment_pkey");

                    b.ToTable("equipment", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("role_pkey");

                    b.ToTable("role", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Discount")
                        .HasColumnType("integer")
                        .HasColumnName("discount");

                    b.Property<int?>("MinTime")
                        .HasColumnType("integer")
                        .HasColumnName("min_time");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<string>("RoomName")
                        .HasColumnType("character varying")
                        .HasColumnName("room_name");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("room_type_id");

                    b.HasKey("RoomId")
                        .HasName("room_pkey");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.RoomEquipment", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.HasKey("RoomId", "EquipmentId")
                        .HasName("pk_room_equipment");

                    b.HasIndex("EquipmentId");

                    b.ToTable("room_equipment", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomTypeId"));

                    b.Property<string>("RoomTypeName")
                        .HasColumnType("character varying")
                        .HasColumnName("room_type_name");

                    b.HasKey("RoomTypeId")
                        .HasName("room_type_pkey");

                    b.ToTable("room_type", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("ServiceName")
                        .HasColumnType("character varying")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("service_pkey");

                    b.ToTable("service", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("character varying")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("character varying")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId")
                        .HasName("user_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user", "coworking");
                });

            modelBuilder.Entity("EquipmentRoom", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomsRoomId")
                        .HasColumnType("integer");

                    b.HasKey("EquipmentId", "RoomsRoomId");

                    b.HasIndex("RoomsRoomId");

                    b.ToTable("EquipmentRoom", "coworking");
                });

            modelBuilder.Entity("Coworking.Models.Booking", b =>
                {
                    b.HasOne("Coworking.Models.BookingStatus", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_booking_status_id_fkey");

                    b.HasOne("Coworking.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_room_id_fkey");

                    b.HasOne("Coworking.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_service_id_fkey");

                    b.HasOne("Coworking.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_user_id_fkey");

                    b.Navigation("BookingStatus");

                    b.Navigation("Room");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coworking.Models.Room", b =>
                {
                    b.HasOne("Coworking.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("room_room_type_id_fkey");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Coworking.Models.RoomEquipment", b =>
                {
                    b.HasOne("Coworking.Models.Equipment", "Equipment")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_equipment_equipment");

                    b.HasOne("Coworking.Models.Room", "Room")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_equipment_room");

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Coworking.Models.User", b =>
                {
                    b.HasOne("Coworking.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EquipmentRoom", b =>
                {
                    b.HasOne("Coworking.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coworking.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coworking.Models.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Coworking.Models.Equipment", b =>
                {
                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("Coworking.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Coworking.Models.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("Coworking.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Coworking.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Coworking.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
